params:
  SKIPPED_FRAMES: 4
  VIDEOS_DIR: 'videos'
  JSONS_DIR: 'jsons'
  CLASSES: [2, 5, 7] # 2 - car, 5 - bus, 7 - truck
  COLUMNS: ['file_name', 'num_cars', 'average_speed_cars', 'num_busses', 'average_speed_busses', 'num_trucks', 'average_speed_trucks']